package com.dp.petshome.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Common implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Byte id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.post_id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Byte postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.user_id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Byte userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.common_content
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private String commonContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.common_praise
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Integer commonPraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.create_time
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.update_time
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_common.status
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_common
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.id
     *
     * @return the value of t_common.id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.id
     *
     * @param id the value for t_common.id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.post_id
     *
     * @return the value of t_common.post_id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Byte getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.post_id
     *
     * @param postId the value for t_common.post_id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setPostId(Byte postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.user_id
     *
     * @return the value of t_common.user_id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Byte getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.user_id
     *
     * @param userId the value for t_common.user_id
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setUserId(Byte userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.common_content
     *
     * @return the value of t_common.common_content
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public String getCommonContent() {
        return commonContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.common_content
     *
     * @param commonContent the value for t_common.common_content
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setCommonContent(String commonContent) {
        this.commonContent = commonContent == null ? null : commonContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.common_praise
     *
     * @return the value of t_common.common_praise
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Integer getCommonPraise() {
        return commonPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.common_praise
     *
     * @param commonPraise the value for t_common.common_praise
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setCommonPraise(Integer commonPraise) {
        this.commonPraise = commonPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.create_time
     *
     * @return the value of t_common.create_time
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.create_time
     *
     * @param createTime the value for t_common.create_time
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.update_time
     *
     * @return the value of t_common.update_time
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.update_time
     *
     * @param updateTime the value for t_common.update_time
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_common.status
     *
     * @return the value of t_common.status
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_common.status
     *
     * @param status the value for t_common.status
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}