package com.dp.petshome.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Pet implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.id
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.pet_name
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private String petName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.pet_age
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private Integer petAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.pet_sex
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private Byte petSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.nature
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private String nature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.head_url
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private String headUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.create_time
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.update_time
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.status
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pet
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.id
     *
     * @return the value of t_pet.id
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.id
     *
     * @param id the value for t_pet.id
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.pet_name
     *
     * @return the value of t_pet.pet_name
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.pet_name
     *
     * @param petName the value for t_pet.pet_name
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.pet_age
     *
     * @return the value of t_pet.pet_age
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public Integer getPetAge() {
        return petAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.pet_age
     *
     * @param petAge the value for t_pet.pet_age
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setPetAge(Integer petAge) {
        this.petAge = petAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.pet_sex
     *
     * @return the value of t_pet.pet_sex
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public Byte getPetSex() {
        return petSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.pet_sex
     *
     * @param petSex the value for t_pet.pet_sex
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setPetSex(Byte petSex) {
        this.petSex = petSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.nature
     *
     * @return the value of t_pet.nature
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.nature
     *
     * @param nature the value for t_pet.nature
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.head_url
     *
     * @return the value of t_pet.head_url
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.head_url
     *
     * @param headUrl the value for t_pet.head_url
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.create_time
     *
     * @return the value of t_pet.create_time
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.create_time
     *
     * @param createTime the value for t_pet.create_time
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.update_time
     *
     * @return the value of t_pet.update_time
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.update_time
     *
     * @param updateTime the value for t_pet.update_time
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.status
     *
     * @return the value of t_pet.status
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.status
     *
     * @param status the value for t_pet.status
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}