package com.dp.petshome.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Post implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.id
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.user_id
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_title
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_content
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private String postContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.post_praise
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private Integer postPraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.create_timne
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private Date createTimne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.update_time
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.status
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_post
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.id
     *
     * @return the value of t_post.id
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.id
     *
     * @param id the value for t_post.id
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.user_id
     *
     * @return the value of t_post.user_id
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.user_id
     *
     * @param userId the value for t_post.user_id
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_title
     *
     * @return the value of t_post.post_title
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_title
     *
     * @param postTitle the value for t_post.post_title
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_content
     *
     * @return the value of t_post.post_content
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_content
     *
     * @param postContent the value for t_post.post_content
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.post_praise
     *
     * @return the value of t_post.post_praise
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public Integer getPostPraise() {
        return postPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.post_praise
     *
     * @param postPraise the value for t_post.post_praise
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setPostPraise(Integer postPraise) {
        this.postPraise = postPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.create_timne
     *
     * @return the value of t_post.create_timne
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public Date getCreateTimne() {
        return createTimne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.create_timne
     *
     * @param createTimne the value for t_post.create_timne
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setCreateTimne(Date createTimne) {
        this.createTimne = createTimne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.update_time
     *
     * @return the value of t_post.update_time
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.update_time
     *
     * @param updateTime the value for t_post.update_time
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.status
     *
     * @return the value of t_post.status
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.status
     *
     * @param status the value for t_post.status
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}