package com.dp.petshome.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class UserAndUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_user.id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_user.interest_id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private Integer interestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_user.interested_id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private Integer interestedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_user.create_time
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_user.update_time
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_and_user.status
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_user.id
     *
     * @return the value of t_user_and_user.id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_user.id
     *
     * @param id the value for t_user_and_user.id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_user.interest_id
     *
     * @return the value of t_user_and_user.interest_id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public Integer getInterestId() {
        return interestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_user.interest_id
     *
     * @param interestId the value for t_user_and_user.interest_id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public void setInterestId(Integer interestId) {
        this.interestId = interestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_user.interested_id
     *
     * @return the value of t_user_and_user.interested_id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public Integer getInterestedId() {
        return interestedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_user.interested_id
     *
     * @param interestedId the value for t_user_and_user.interested_id
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public void setInterestedId(Integer interestedId) {
        this.interestedId = interestedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_user.create_time
     *
     * @return the value of t_user_and_user.create_time
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_user.create_time
     *
     * @param createTime the value for t_user_and_user.create_time
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_user.update_time
     *
     * @return the value of t_user_and_user.update_time
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_user.update_time
     *
     * @param updateTime the value for t_user_and_user.update_time
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_and_user.status
     *
     * @return the value of t_user_and_user.status
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_and_user.status
     *
     * @param status the value for t_user_and_user.status
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}