package com.dp.petshome.persistence.dao;

import com.dp.petshome.persistence.model.Common;

public interface CommonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    int insert(Common record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    int insertSelective(Common record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    Common selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    int updateByPrimaryKeySelective(Common record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_common
     *
     * @mbggenerated Sat Mar 25 17:54:26 CST 2017
     */
    int updateByPrimaryKey(Common record);
}