package com.dp.petshome.persistence.dao;

import com.dp.petshome.persistence.model.Pet;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    Pet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    int updateByPrimaryKeySelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated Sat Mar 25 17:53:09 CST 2017
     */
    int updateByPrimaryKey(Pet record);
}