package com.dp.petshome.persistence.dao;

import com.dp.petshome.persistence.model.Post;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Sat Mar 25 17:53:57 CST 2017
     */
    int updateByPrimaryKey(Post record);
}