package com.dp.petshome.persistence.dao;

import com.dp.petshome.persistence.model.PostAndUser;

public interface PostAndUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:13 CST 2017
     */
    int insert(PostAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:13 CST 2017
     */
    int insertSelective(PostAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:13 CST 2017
     */
    PostAndUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:13 CST 2017
     */
    int updateByPrimaryKeySelective(PostAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:13 CST 2017
     */
    int updateByPrimaryKey(PostAndUser record);
}