package com.dp.petshome.persistence.dao;

import com.dp.petshome.persistence.model.UserAndUser;

public interface UserAndUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    int insert(UserAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    int insertSelective(UserAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    UserAndUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    int updateByPrimaryKeySelective(UserAndUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_and_user
     *
     * @mbggenerated Sat Mar 25 17:56:52 CST 2017
     */
    int updateByPrimaryKey(UserAndUser record);
}